# Generated by Django 4.0.2 on 2022-05-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('abstract', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query_Document1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_ID', models.IntegerField()),
                ('document_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuerySet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='references1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('doc2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.dataset1')),
            ],
        ),
    ]
